Update cleanupscript

diff --git a/cleanupscript b/cleanupscript
--- a/cleanupscript
+++ b/cleanupscript
@@ -1,1 +1,83 @@
 
+Example 2-1. cleanup: A script to clean up log files in /var/log
+
+# Cleanup
+# Run as root, of course.
+cd /var/log
+cat /dev/null > messages
+cat /dev/null > wtmp
+echo "Log files cleaned up."
+
+Example 2-2. cleanup: An improved clean-up script
+
+#!/bin/bash
+# Proper header for a Bash script.
+# Cleanup, version 2
+# Run as root, of course.
+# Insert code here to print error message and exit if not root.
+
+LOG_DIR=/var/log
+# Variables are better than hard-coded values.
+cd $LOG_DIR
+cat /dev/null > messages
+cat /dev/null > wtmp
+
+echo "Logs cleaned up."
+exit # The right and proper method of "exiting" from a script.
+ # A bare "exit" (no parameter) returns the exit status
+ #+ of the preceding command. 
+ 
+Example 2-3. cleanup: An enhanced and generalized version of above scripts. 
+
+#!/bin/bash
+# Cleanup, version 3
+# Warning:
+# -------
+# This script uses quite a number of features that will be explained
+#+ later on.
+# By the time you've finished the first half of the book,
+#+ there should be nothing mysterious about it.
+LOG_DIR=/var/log
+ROOT_UID=0 # Only users with $UID 0 have root privileges.
+LINES=50 # Default number of lines saved.
+E_XCD=86 # Can't change directory?
+E_NOTROOT=87 # Non-root exit error.
+# Run as root, of course.
+if [ "$UID" -ne "$ROOT_UID" ]
+then
+echo "Must be root to run this script."
+exit $E_NOTROOT
+fi
+if [ -n "$1" ]
+# Test whether command-line argument is present (non-empty).
+then
+lines=$1
+else
+lines=$LINES # Default, if not specified on command-line.
+fi
+# Stephane Chazelas suggests the following,
+#+ as a better way of checking command-line arguments,
+#+ but this is still a bit advanced for this stage of the tutorial.
+#
+# E_WRONGARGS=85 # Non-numerical argument (bad argument format).
+#
+# case "$1" in
+# "" ) lines=50;;
+# *[!0-9]*) echo "Usage: `basename $0` lines-to-cleanup";
+# exit $E_WRONGARGS;;
+# * ) lines=$1;;
+# esac
+#
+#* Skip ahead to "Loops" chapter to decipher all this.
+cd $LOG_DIR
+if [ `pwd` != "$LOG_DIR" ] # or if [ "$PWD" != "$LOG_DIR" ]
+# Not in /var/log?
+then
+echo "Can't change to $LOG_DIR."
+exit $E_XCD
+fi # Doublecheck if in right directory before messing with log file.
+# Far more efficient is:
+#
+# cd /var/log || {
+# echo "Cannot change to necessary directory." >&2
+# exit $E_XCD;
